config/routes.rb
ProjectManagementSystem::Application.routes.draw do

  devise_for :people, :controllers => { :registrations => 'registrations' }

  resources :projects do
    resources :task_groups
  end

  resources :task_groups do
    resources :tasks
  end

  resources :tasks do
    resource :person
  end

  root :to => "projects#index"
end

app/models/person.rb
class Person < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  belongs_to :task

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :project_title , :presence => true
  validates :project_description , :presence => true

  has_many :task_groups , :dependent => :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :title , :presence => true
  validates :description , :presence => true

  belongs_to :task_group
  has_one :person
end

app/models/task_group.rb
class TaskGroup < ActiveRecord::Base

  validates :group_title , :presence =>true
  validates :group_description , :presence =>true

  belongs_to :project
  has_many :tasks, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def new
    @task = Task.find(params[:task_id])
    puts @task.inspect
    @person = Person.new
  end

  def create
    @task = Task.find(params[:task_id])
    @person = Person.new(params[:person])
    @person.task_id = params[:task_id]
    if @person.save
      redirect_to task_path(@task), :notice => "New Person Added Successfully !!"
    else
      render "new"
    end
  end

  def destroy
    @task = Task.find(params[:task_id])
    @person = @task.person.find(params[:person])
    if @person.destroy
      redirect_to task_path(@task)
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_person!

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
    # @peo = Person.all
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to projects_path, :notice => "New Project Created Successfully !!"
    else
      render "new"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy]
  include Devise::Controllers::InternalHelpers

  def create
    super
    UserMailer.welcome(@person).deliver
  end

end

app/controllers/task_groups_controller.rb
class TaskGroupsController < ApplicationController

  before_filter :authenticate_person!

  def new
    @project = Project.find(params[:project_id])
    @task_group = @project.task_groups.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task_group = @project.task_groups.create(params[:task_group])
    if @task_group.save
      redirect_to project_path(@project), :notice => "New Task Group Added Successfully !!"
    else
      render "new"
    end

  end

  def show
    @project = Project.find(params[:project_id])
    @task_group = @project.task_groups.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task_group = @project.task_groups.find(params[:id])
    if @task_group.destroy
      redirect_to project_path(@project)
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_filter :authenticate_person!

  def new
    @task_group = TaskGroup.find(params[:task_group_id])
    @task = @task_group.tasks.new
  end

  def create
    @task_group = TaskGroup.find(params[:task_group_id])
    @task = @task_group.tasks.create(params[:task])
    if @task.save
      redirect_to project_task_group_path(@task_group.project, @task_group), :notice => "New Task Added to the Group Successfully !!"
    else
      render "new"
    end
  end

  def show
    @task_group = TaskGroup.find(params[:task_group_id])
    @task = @task_group.tasks.find(params[:id])
   end

  def destroy
    @task_group = TaskGroup.find(params[:task_group_id])
    @task = @task_group.tasks.find(params[:id])
    if @task.destroy
      redirect_to project_task_group_path(@task_group.project, @task_group)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_groups_helper.rb
module TaskGroupsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagementSystem</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= notice %>
<%= alert %>
<%= render :partial => "devise/shared/links" %>
<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<h4>Assign a Member </h4>

<%= semantic_form_for([@task,@person]) do |f| %>
  <%= f.inputs :person => "Basic" do %>
    <%= f.input :name , :input_html => { :class => 'autogrow'} %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/people/new.html.erb
<%= render "form" %>

app/views/projects/_form.html.erb
<%= semantic_form_for @project do |form| %>

<%= form.inputs :project => "Basic" do %>
<%= form.input :project_title , :input_html => { :class => 'autogrow'} %>
<%= form.input :project_description , :input_html => { :class => 'autogrow', :rows => 5}%>

<%= form.buttons do %>
<%= form.commit_button %>
<% end %>

<% end %>

<% end %>

app/views/projects/_project.html.erb
<ul>
  <li>
    <%= link_to project.project_title , project_path(project) %>
    <%= link_to "Remove" , project_path(project), :method => :delete, :confirm => "Delete, are u Sure ??" %>
  </li>
</ul>

app/views/projects/index.html.erb
<h1> All projects </h1>

<%= render @projects %>

<%= link_to "Create a New Project" , new_project_path %>

app/views/projects/new.html.erb
<h1> New project </h1>

<%= render "form" %>

<%= link_to "Back to Index", projects_path %>

app/views/projects/show.html.erb
<h1> Showing project </h1>

<label> Title : </label>  <%= @project.project_title %> <br/ >
<label> Project Description : </label> <%= @project.project_description %> <br/ >

<div class="task_group_class">
  <h4> All Task Groups </h4>
  <% @project.task_groups.each do |tg|%>
  <label> Task Group Title : </label>  <%= link_to tg.group_title , project_task_group_path(@project,tg)%> <br/ >
  <label> Task Group Description : </label> <%= tg.group_description %> <br/ >
  <%= link_to "Remove Task Group", project_task_group_path(@project,tg), :method => :delete, :confirm => "Delete, are u Sure ??" %> <br/ >
  <% end %>

  <%= link_to "Add a Task Group", new_project_task_group_path(@project) %>
</div>


<%= link_to "Back to Index", projects_path %>

app/views/task_groups/_form.html.erb
<h4> Showing task group form </h4>

<% semantic_form_for ([@project,@task_group]) do |group_form| %>

<% group_form.inputs :task_group => "Basic" do %>
<%= group_form.input :group_title , :input_html => { :class => 'autogrow'} %>
<%= group_form.input :group_description , :input_html => { :class => 'autogrow', :rows => 5} %>

<% group_form.buttons do %>
<%= group_form.commit_button %>
<% end %>

<% end %>

<% end %>

app/views/task_groups/new.html.erb
<%= render "task_groups/form" %>

app/views/task_groups/show.html.erb
<h3> Showing Tasks of Group <%= @task_group.group_title %>  </h3>

<div class="task_class">
  <h4>All The Tasks</h4>
  <% @task_group.tasks.each do |t|%>
  <label> Task Title : </label>  <%= link_to t.title, task_group_task_path(@task_group,t) %> <br/ >
  <label> Task Description : </label> <%= t.description %> <br/ >
  <%= link_to "Remove Task", task_group_task_path(@task_group,t), :method => :delete, :confirm => "Delete, are u Sure ??" %> <br/ >
  <% end %>

  <%= link_to "Add a Task", new_task_group_task_path(@task_group) %> <br />
</div>

<%= link_to "Back to Project", project_path(@project) %>

app/views/tasks/_form.html.erb
<h4> Showing task form </h4>

<%= semantic_form_for([@task_group,@task]) do |task_form| %>
<%= task_form.inputs :task => "Basic" do %>
<%= task_form.input :title , :input_html => { :class => 'autogrow'} %>
<%= task_form.input :description , :input_html => { :class => 'autogrow', :rows => 5} %>
<%= task_form.buttons do %>
<%= task_form.commit_button %>
<% end %>
<% end %>
<% end %>

app/views/tasks/new.html.erb
<%= render "tasks/form" %>

app/views/tasks/show.html.erb
<h3>Assigned Member of <%= @task.title %>  </h3>

<div class="member_class">
  <% if @task.person != nil %>
    <label> Member : </label>  <%= @task.person.name %> <br/ >
    <%= link_to "Remove Member", task_person_path(@task,@person), :method => :delete, :confirm => "Delete, are u Sure ??" %> <br/ >
  <% else %>
    <%= link_to "Assign a Member" , new_task_person_path(@task) %>
  <% end %>
</div>

<%= link_to "Back to Task", task_path(@task) %>